{% set version = "3.0.2" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: eb1c77514cf22cd1a6af449f8a619fb484da7acf54f635a7ae9030e81e5424bb

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main
    - luigi-deps-tree = luigi.tools.deps_tree:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=5.0,<7
    # cf doesn't have this package to satisfy this dependency on win
    # - python-daemon <2.2.0  # [win]
    - python-daemon  # [not win]
    - python-dateutil >=2.7.5,<3
    - enum34 >1.1.0  # [py<34]
    - prometheus_client ==0.5.0
    - toml <2.0.0

test:
  requires:
    - pip
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - pip check  # [not win]

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Workflow mgmgt + task scheduling + dependency resolution.
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
