{% set name = "luigi" %}
{% set version = "2.7.7" %}
{% set sha256 = "9335ffb101413ccba92dca2b34bfa0387f1a08c41c65df538fd0e3fe424d3155" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/spotify/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - pyparsing
    - tornado >=4.0,<5
    - python-daemon <3.0  # [not win]
    - botocore

test:
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
