{% set version = "3.2.0" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: c8e48d48338f73fd1071654988cdc1725fc13b6b9b9c2f7532241e11994a420b

build:
  number: 0
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main
    - luigi-deps-tree = luigi.tools.deps_tree:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=5.0,<7
    - python-dateutil >=2.7.5,<3
    - tenacity >=8,<9
    # extras
    - prometheus_client ==0.5.0
    - toml <2.0.0
    # cf doesn't have this package to satisfy this dependency on win
    # - python-daemon <2.2.0  # [win]
    - python-daemon  # [not win]

test:
  requires:
    - pip
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - pip check  # [not win]

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Workflow mgmgt + task scheduling + dependency resolution.
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
